apiVersion: apps/v1
kind: Deployment
metadata:
  name: nhl-app-fe-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nhl-app-fe
        image: karamel32/nhl_app:0.1.0
        imagePullPolicy: Always 
        ports:
        - containerPort: 80
        env:
          - name: ENV_BACKEND_URI
            valueFrom:
              configMapKeyRef:
                name: fe-configmap
                key: env_backend_uri
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            cpu: 500m
            memory: 500Mi
