---
apiVersion: v1
kind: Service
metadata:
  name: nhl-app-fe-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
      app: frontend
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: nhl-app-fe-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
      app: frontend
  type: ClusterIP
