apiVersion: apps/v1
kind: Deployment
metadata:
  name: nhl-app-fe-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nhl-app-fe
        image: karamel32/nhl_app:0.0.7
        imagePullPolicy: Always 
        ports:
        - containerPort: 80
        env:
          - name: ENV_BACKEND_URI
            valueFrom:
              configMapKeyRef:
                name: fe-configmap
                key: env_backend_uri
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: nhl-app-fe-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
      app: frontend
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nhl-app-fe-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /(nhl_app|favicon.ico)
        pathType: ImplementationSpecific
        backend:
          service:
            name: nhl-app-fe-svc
            port:
              number: 80
