---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: flask-pvc
  namespace: main
spec:
  storageClassName: azurefile
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
