apiVersion: apps/v1
kind: Deployment
metadata:
  name: nhl-app-fe-deployment
  namespace: __NAMESPACE__
  labels:
    name: frontend-nhl-app
    instance: app
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend-nhl-app
      instance: app
      component: frontend
  template:
    metadata:
      labels:
        name: frontend-nhl-app
        instance: app
        component: frontend
    spec:
      containers:
      - name: nhl-app-fe
        image: karamel32/nhl_app:__BUILD_VERSION__
        imagePullPolicy: Always 
        ports:
        - containerPort: 80
          name: http
        env:
          - name: ENV_BACKEND_URI
            valueFrom:
              configMapKeyRef:
                name: fe-configmap
                key: env_backend_uri
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            cpu: 500m
            memory: 500Mi
