metadata:
  labels:
    some-label: pod-runner
spec:
  containers:
  - name: docker
    image: docker:19.03.13-dind
    command:
    - dockerd
    args:
    - --host=unix:///var/run/docker.sock
    - --storage-driver=overlay
    tty: true
    securityContext:
      privileged: true
