apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nhl-apps-be-metrics
  labels:
      release: monitoring
      component: backend
      instance: app
      name: backend-nhl-app
  namespace: monitoring
spec:
  endpoints:
  - path: /metrics
    port: http
    interval: 30s
  selector:
    matchLabels:
      component: backend
      instance: app
      name: backend-nhl-app
  namespaceSelector:
    matchNames:
    - main
    - dev
