apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nhl-apps-metrics
  labels:
      release: monitoring
      app: frontend
      instance: app
      component: frontend    
  namespace: monitoring
spec:
  endpoints:
  - path: /metrics
    port: http
    interval: 30s
  selector:
    matchLabels:
      app: frontend
      instance: app
      component: frontend
  namespaceSelector:
    matchNames:
    - main
    - dev
